version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nest_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_template
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

  mongodb:
    image: mongo:7
    container_name: nest_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - nest_network

  redis:
    image: redis:7-alpine
    container_name: nest_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - nest_network

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  nest_network:
    driver: bridge



